### ISSUE TITLE
broken links to source

### ISSUE THREAD

**Issue by slowkow** [fastai/deck_of_cards#1]
I'm at this page:

https://fastai.github.io/deck_of_cards/deck.html#Deck

I decided to click `[source]` to see the source code for Deck, but the link goes here:

    https://github.com/hamelsmu/deck_of_cards/tree/master/deck_of_cards/deck.py#L9

I think the correct link is supposed to be:

    https://github.com/fastai/deck_of_cards/blob/master/deck_of_cards/deck.py#L9

So, it seems we need two changes:

- Change "hamelsmu" to "fastai"
- Change "tree" to "blob"

**Comment by hamelsmu** [comment]
Thanks this has been fixed.  Although there remains an issue with links to dunder methods that we are aware of.
